[settings]
known_third_party = ["eve", "pymongo", "requests", "setuptools", "six"]

[tool.black]
safe = true
quiet = true
skip-string-normalization = true

[pycodestyle]
max-line-length = 88

[flake8]
max-line-length = 88
